### ISSUE TITLE
LD_blocks.bed calculated by 1000Genomes

### ISSUE THREAD

**Issue by wei110110** [jmacdon/LDblocks_GRCh38#2]
Hello,
Thank you very much for your great and generous sharing. 
Even with tutorials, it can still be challenging for those less familiar with programming languages.

I noticed that you released pyrho_EAS_LD_blocks.bed. Does this imply the use of GRCh38-based 1000Genomes data and new sex-averaged dense recombination rate data from either deCode Genetics or pyrho?

I would like to ask if you have simply used the LD_blocks.bed calculated by 1000Genomes? 
Additionally, do you think there is a significant difference between this approach and what you have currently released?

Wei

**Comment by jmacdon** [comment]
The bed files with pyrho in the name are meant to  indicate that Pyrho was used to generate the data. I am not familiar with the LD blocks generated by 1000 Genomes, and cannot say how they may compare with the blocks we generated.
