### ISSUE TITLE
What is Effective Population Size?

### ISSUE THREAD

**Issue by Sohambiswas8** [jmacdon/LDblocks_GRCh38#3]
Hello, 

Thank you for the well-detailed tutorial. After chromosome partitioning, during computing covariance, there is an argument for effective population size. What is this exactly? Does it mean that my genotyped sample data have been created from how many samples (drawn for sequencing or chip-array experiment)? e.g. I have a genotype data for 484 individuals. But these 484 individuals come from a sequencing experiment with 15000 whole genomes in a single population. So in my case, will the effective population size be 15000? Is it so or am I missing something?

**Comment by jmacdon** [comment]
Effective population size is an estimated value based on the population, not a particular sample size. There are different ways to compute it, for example see here. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1832099/
