### ISSUE TITLE
Calculation of Covariance Matrix

### ISSUE THREAD

**Issue by Sohambiswas8** [jmacdon/LDblocks_GRCh38#4]
Hello, 
Thank you for your previous reply.
As you told in [issue #3 ](https://github.com/jmacdon/LDblocks_GRCh38/issues/3) I used [SNep](https://www.frontiersin.org/journals/genetics/articles/10.3389/fgene.2015.00109/full) tool for estimating effective population over a certain number of generations. 

1) In your work you have specified Ne for EUR as 11418. Is this `Ne` of current generation? Since I have generated a list of `Ne` estimates across different generations, I was wondering from which generation `Ne` need to be specified. My final goal is the same as you have done, creating LD blocks for SNP genotype data. 

2) Also, for calculating covariance matrix, the cut-off beneath which covariance is not reported needs to be specified, which you set as 1e-07. How to determine this cut-off? if possible, can you provide any work where it is mentioned clearly? (My primary thought was covariance and correlation between SNPs i.e. in terms `r` or `r-squared` are not same. But need to verify) 

Thanking you, 
Soham

**Comment by jmacdon** [comment]
1.) I don't remember. I found that in a recent paper, but as I am sure you are well aware, different people get different results. I am not sure it's possible to say which value is 'correct', so I picked one and went with it.
2.) I believe this is the same number that was specified in the original paper that described the method.

**Comment by Sohambiswas8** [comment]
Hi, 

Thank you again for your reply. Can you please share the paper where you come across the number? As I see most of the works are based on EUR or AMR populations, my concern is to calculate it for Indian populations which will be part of SAS panel.

**Comment by jmacdon** [comment]
I don't recall the paper, sorry.
