### ISSUE TITLE
UCSC track hub?

### ISSUE THREAD

**Issue by maximilianh** [jmacdon/LDblocks_GRCh38#6]
Hi, have you considered making a UCSC track hub from your data, so it's easier to visualize on the various genome browsers? IGV, Ensembl and I think NCBI browsers now also support track hubs... 

(I wasn't able to find a contact email on the preprint, hence this ticket)

**Comment by jmacdon** [comment]
They are small BED files that anybody can submit to UCSC themselves if they want to visualize. I can't imagine there is any value add by me making a track hub.
