### ISSUE TITLE
Questions regarding step 4: 'remove all but the low-pass filter...'

### ISSUE THREAD

**Issue by Gujmin** [jmacdon/LDblocks_GRCh38#8]
Thank you very much for your insights. I had been running Step 4 for a long time without getting results, but your work has been very enlightening. However, when I commented out lines 67-78 of the code in Step 4, I encountered an error:

```
Traceback (most recent call last):
  File "/disk194/gujm/software/ldetect/ldetect/examples/P02_minima_pipeline.py", line 233, in <module>
    cl.commander_line((pipeline))
  File "/home/gujm/miniconda3/envs/ldetect/lib/python3.6/site-packages/commanderline/commander_line.py", line 366, in commander_line
    return_value = func(**unwrap_options)
  File "/disk194/gujm/software/ldetect/ldetect/examples/P02_minima_pipeline.py", line 75, in pipeline
    metric_out_uniform = apply_metric(chr_name, begin, end, config, breakpoint_loci_uniform)
NameError: name 'breakpoint_loci_uniform' is not defined
```

Looking at the code, I noticed that subsequent steps also use the variables `metric_out_uniform` and `breakpoint_loci_uniform`. Directly commenting them out may not be appropriate. Should I uncomment lines 69-70 and comment out lines 71-72 instead?

**Comment by jmacdon** [comment]
Did you comment out lines 103-105 in P02_minima_pipeline.py?

**Comment by Gujmin** [comment]
> Did you comment out lines 103-105 in P02_minima_pipeline.py?

YES,I have already commented out lines 103-105 in P02_minima_pipeline.py

**Comment by jmacdon** [comment]
In that case I don't know what to tell you. This GitHub is really just meant to provide the LDblocks, and I cannot provide support for detect, since that's not my code.
